### ISSUE TITLE
[feature request] teaspoon options passed to guard teaspoon

### ISSUE THREAD

**Issue by GetContented** [modeset/guard-teaspoon#33]
First up, I **freaking love** guard-teaspoon and teaspoon. <3 Thank you so much for these projects.

At the moment when guard runs, it doesn't seem to be respecting the setup I have in my teaspoon_env. Using latest versions of both teaspoon and guard-teaspoon (teaspoon 0.8.0, and git following gem on guard-teaspoon (so the latest head I think)).

In particular, the output settings don't seem to be respected.

I have this in my teaspoon_env.rb file:
    config.formatters = ["documentation"]

And this is the guard command in the guardfile for teaspoon:
     guard 'teaspoon', environment: "spec/teaspoon_env.rb" do

I've tried passing the cli option but it doesn't seem to respect it. Apologies in advance if this is something I've done and not understood...

**Comment by rharriso** [comment]
I was able to get coverage to work by passing an argument to the guard options
```
guard :teaspoon, use_coverage: true do 
  ...
end
```

Is it save to say that all Teaspoon [console arguments](https://github.com/modeset/teaspoon/blob/2169671a13aed097447b3c4b2cdfe46081e7fbf9/lib/teaspoon/command_line.rb#L35) can be passed?

**Comment by GetContented** [comment]
I'm not interested in this anymore, so closing.

**Comment by FinnWoelm** [comment]
This is old, but for anyone looking for the solution (such as myself), **you can change tho formatting**.

Simply add `formatters: "documentation"` to your Guardfile, so that it becomes

    guard :teaspoon, formatters: "documentation" do
       ....
    end

Here are some of the available formats: `:dot, :clean, :documentation, :json, :junit, :pride, :rspec_html, :snowday, :swayze_or_oprah, :tap, :tap_y, :teamcity`

You can find more config options for guard-teaspoon in this file: https://github.com/jejacks0n/guard-teaspoon/blob/master/lib/guard/teaspoon.rb
